spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/labo
    username: root
    password: supersecret
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
